sudo: required

language: java

dist: trusty

jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

services:
  - docker

env:
  - DOCKER_IMAGE=jkrajnc11/products-service

script:
  - mvn clean install -U
  - docker build -t "$DOCKER_IMAGE" .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push "$DOCKER_IMAGE"

